const GAMEPLAY = {
  MATCH_DURATION_MS: 15 * 60 * 1000,
  COUNTDOWN_DURATION_MS: 20 * 1000,

  SCENARIO_COUNT: 6,

  SCENARIO_INTERVAL_MS: 2.5 * 60 * 1000,

  FIRST_SCENARIO_DELAY_MS: 0,

  INVESTIGATION_WINDOW_MS: 2 * 60 * 1000,

  PUBLICATION_GRACE_MS: 30 * 1000,

  COUNTDOWN_DURATION_MS: 20 * 1000,

  BACKGROUND_NEWS_MIN: 3,
  BACKGROUND_NEWS_MAX: 5,

  SCORING: {
    SUPPORTED_CLAIM: 10,
    UNSUPPORTED_CLAIM: -12,
    CRITICAL_FALSE_CLAIM: -25,
    IMPORTANT_HIDDEN_FACT_OMITTED: -5,
    LOW_SENSATIONALISM_THRESHOLD: 20,
    LOW_SENSATIONALISM_BONUS: 5,
    HIGH_SENSATIONALISM_THRESHOLD: 50,
    HIGH_SENSATIONALISM_PENALTY: -15,
    EVIDENCE_PROPERLY_CITED: 10,
    LATE_PUBLICATION_PENALTY: -10,
    MISSING_FACT_PENALTY: -5,
    FALSE_CLAIM_PENALTY: -15,
  },
};

Object.freeze(GAMEPLAY);

module.exports = { GAMEPLAY };
